config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :articles
  resources :jobs do
    resources :jobs_applications, only: :create
  end
  resources :skills, only: [] do
    get "search", on: :collection
  end
  resources :activities, only: [:index]
  resources :followings_jobs, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :followings_users, only: [:create, :destroy]
    resources :messages do
      get "messages-unread", on: :collection
    end
    resources :chatrooms, only: :show do
      post "mark-as-read", on: :member
    end
    resources :recommandations, only: :create
  end
  namespace :my do
    resources :users, only: [:show] do
      resources :users_skills
      resources :experiences
      resources :jobs
      resources :jobs_applications, only: [] do
        get 'my-jobs-applications', on: :collection
        get 'my-jobs-applicants', on: :collection
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include PgSearch::Model

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  enum role: [:candidate, :recruiter]

  attr_writer :login

  # see if can remove user_
  has_many :followees, class_name: 'FollowingsUser', foreign_key: :followee_id
  has_many :followers, class_name: 'FollowingsUser', foreign_key: :follower_id
  has_many :messages, dependent: :destroy
  has_many :chatrooms, -> { distinct }, through: :messages
  has_many :users_skills, dependent: :destroy
  has_many :skills, through: :users_skills
  has_many :experiences, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :jobs_applications, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :followings_jobs, dependent: :destroy
  has_one_attached :profile_picture

  validates :first_name, :last_name, :username, :job_position, :about_me, presence: true
  validates :username, uniqueness: { case_sensitive: false }, length: { minimum: 3 }
  validates :about_me, length: { minimum: 20 }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  validates :password, format: { with: /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/,
                                 message: "Complexity requirement not met. Please use: 1 uppercase,
                                  1 lowercase, 1 digit and 1 special character" }

  pg_search_scope :global_search,
    against: [:username, :job_position, :role],
    associated_against: {
      skills: [:name],
      experiences: [:content]
    },
    using: {
      tsearch: { prefix: true }
    }

  def role=(value)
    value = value.to_i if value.is_a? String
    super(value)
  end

  def find_or_create_chatroom_with(other_user)
    # chatroom = Chatroom.eager_load(:messages).where(
    #   messages: { user_id: self.id },
    #   messages: { user_id: other_user.id }
    # ).first
    chatroom = Chatroom.where("name = ? or name = ?", "#{self.username} - #{other_user.username}", "#{other_user.username} - #{self.username}").first

    if chatroom.nil?
      chatroom = Chatroom.create(name: "#{self.username} - #{other_user.username}")
      Message.create(user: self, chatroom: chatroom, content: "subscription", read: true)
      Message.create(user: other_user, chatroom: chatroom, content: "subscription", read: true)
    end
    return chatroom
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/my/users_controller.rb
class My::UsersController < ApplicationController
  def show
    @current_users_skills = UsersSkill.where(user: current_user, previous_skills: false)
    @previous_users_skills = UsersSkill.where(user: current_user, previous_skills: true)
    @experiences = Experience.where(user: current_user).order(start_date: :desc)
    @pagy, @jobs = pagy(current_user.jobs, items: 8)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    if params[:query] && !params[:query].empty?
      # if params[:query] =~ /(r|R){1}(e|E){1}(c|C){1}(r|R)?(u|U)?(i|I)?(t|T)?(e|E)?(r|R)?/
      #   @query = 1
      # elsif params[:query] =~ /(c|C){1}(a|A){1}(n|N){1}(d|D)?(i|I)?(d|D)?(a|A)?(t|T)?(e|E)?/
      #   @query = 0
      # end
      @role = SearchRole.new(params[:query])
      @search_roles = User.where(role: @role.get_role).where.not(visible: false, confirmed_at: nil, id: current_user)
      @full_search_array = @search_roles + User.global_search(params[:query]).where.not(visible: false, confirmed_at: nil, id: current_user)
      @full_search = User.where(id: @full_search_array.map(&:id))
      @pagy, @users = pagy(@full_search, items: 12)
    else
      @pagy, @users = pagy(User.where.not(visible: false, confirmed_at: nil, id: current_user), items: 12)
    end
  end

  def show
    @current_users_skills = UsersSkill.where(user: @user, previous_skills: false)
    @previous_users_skills = UsersSkill.where(user: @user, previous_skills: true)
    @experiences = Experience.where(user: @user).order(start_date: :desc)
    @pagy, @jobs = pagy(@user.jobs, items: 8)
    @message = Message.new
    @chatroom = current_user.find_or_create_chatroom_with(@user)
    @message.chatroom = @chatroom
    @recommandation = Recommandation.new
    @followings_user = FollowingsUser.where(followee: params[:id], follower: current_user).first
    @followings_user = FollowingsUser.new unless @followings_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="card rounded-lg">
    <div class="card-header">
      <h1>All of our users</h1>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-12 col-md-8">
          <%= form_tag users_path, method: :get, class: "form-inline mb-3" do %>
          <table>
            <tr>
              <td>
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control rounded-pill",
                  type: "search",
                  placeholder: "Find a user"
                %>

              </td>
              <td>

            <%= submit_tag "Search", class: "btn btn-outline-primary rounded-pill mt-auto" %>
              </td>
            </tr>
          </table>
          <% end %>

        </div>
        <div class="col-12 col-md-3 m-auto">
          <%== pagy_bootstrap_nav(@pagy) %>

        </div>
      </div>
      <hr>
      <br>
      <% if @users.empty? %>
        <p>No results found.</p>
      <% end -%>
      <div class="cards">
        <% @users.each do |user| %>
          <div class="card-user rounded-pill">
            <% if user.profile_picture.attached? %>
                <%= cl_image_tag user.profile_picture.key, class: "avatar" %>
            <% else %>
               <%= image_tag "no-avatar.png", class: "avatar" %>
            <% end -%>
            <div class="card-user-infos">
              <h2><%= link_to user.username, user_path(user) %></h2>
              <p><%= user.job_position %></p>
              <p><%= user.role.capitalize %></p>
            </div>
          </div>
        <% end -%>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="card rounded-lg mb-3">
    <div class="card-header text-center">
      <h1>
        <% if @user.profile_picture.attached? %>
          <%= cl_image_tag @user.profile_picture.key, class: "avatar-large" %>
        <% else %>
          <%= image_tag "no-avatar.png", class: "avatar-large" %>
        <% end -%>
        <%= @user.username %>'s profile
      </h1>
    </div>
    <div class="card-body">
      <div class="row mb-3 justify-content-center">
        <div class="col-12">
          <table class="m-auto">
            <tr>
              <td>
                <% unless @followings_user.id %>
                  <%= simple_form_for([ @user, @followings_user]) do |f|%>
                    <%= f.button :submit, value: "Follow", class: "btn btn-outline-primary rounded-pill" %>
                  <% end -%>
                <% else %>
                  <%= link_to 'Unfollow', user_followings_user_path(@user, @followings_user), method: :delete, class: 'btn btn-outline-warning rounded-pill' %>
                <% end -%>
              </td>
            <%#= link_to 'Send a message', new_user_message_path(@user),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-message', class: 'btn btn-outline-primary'}  %>
              <td>
                <button id="send-message" data-user-id="<%= @user.id %>" data-chatroom-id="<%= @chatroom.id %>" class="btn btn-outline-primary rounded-pill" data-toggle="modal" data-target="#modal-message">Send a message</button>
              </td>

            </tr>
          </table>
        </div>
      </div>

    </div>
  </div>

  <div id="modal-message" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Send a message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
            <div id="content">
            <% @chatroom.messages.all.each do |message| %>
              <% unless message.content == "subscription" %>
                <% html = "<strong>#{message.content}</strong>".html_safe %>
                <p><%= message.user.username %>: <%= message.read == false && message.user != current_user ? html : message.content %></p>
              <% end -%>
            <% end -%>
            </div>
          </div>
          <%= simple_form_for([@user, @message], remote: true) do |f| %>
            <%= f.input :chatroom_id, as: :hidden, value: @message.chatroom.id %>
            <%= f.input :content %>
            <%= f.button :submit,value: "Send Message", class: 'btn btn-outline-primary btn-block' %>
          <% end -%>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>
      </div>

    </div>
  </div>

  <div class="row mb-3">
    <div class="col-12">
      <div class="card rounded-lg">
        <div class="card-header text-center">
          <h2>About me</h2>

        </div>
        <div class="card-body text-center">
          <p><%= @user.about_me %></p>

        </div>
      </div>
    </div>
  </div>
    <% if @user.role == "candidate" %>
      <div class="row mb-3">
        <div class="col-12 col-lg-6">
          <div class="card rounded-lg mb-3">
            <div class="card-header text-center">
              <h2>Current skills</h2>
            </div>
            <div class="card-body">


              <% unless @current_users_skills.blank? %>
                <% @current_users_skills.each do |user_skill| %>


                  <div class="card-skill">
                    <div class="card-skill-infos mr-auto">
                      <h2><%= user_skill.skill.name %></h2>
                      <!-- <p><%#= user_skill.level.capitalize %></p> -->
                      <div class="d-flex"><%= "<div class='level'></div>".html_safe * (UsersSkill.levels[user_skill.level]+1) %></div>

                    </div>
                    <span class="btn btn-outline-primary rounded-pill mr-4" data-toggle="modal" data-target="#modal-recommandation-<%= user_skill.id %>">Recommend</span>
                  </div>

                  <div id="modal-recommandation-<%= user_skill.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title">Recommend this user</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <% @recommandation.users_skill = user_skill %>
                          <%= simple_form_for([@user, @recommandation], remote: true) do |f| %>
                            <%= f.input :users_skill_id, as: :hidden, value: @recommandation.users_skill.id %>
                            <%= f.input :content %>
                            <%= f.button :submit, class: 'btn btn-outline-primary' %>
                          <% end -%>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                        </div>
                      </div>
                    </div>
                  </div>
                  <% unless user_skill.recommandations.blank? %>
                    <div class="recommandations">
                      <h5>Recommendations</h5>
                      <div class="recommendations-list">
                        <div>
                          <% user_skill.recommandations.each do |recommandation| %>
                            <p><%= recommandation.user.username %>: <%= recommandation.content %></p>
                          <% end -%>

                        </div>
                      </div>

                    </div>
                  <% end -%>
                <% end -%>
              <% else %>
                <p>No current skills.</p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="card mb-3 rounded-lg">
            <div class="card-header text-center">
              <h2>Previous skills</h2>
            </div>
            <div class="card-body">


              <% unless @previous_users_skills.blank? %>
                <% @previous_users_skills.each do |user_skill| %>
                  <div class="card-skill previous-skills">
                    <div class="card-skill-infos mr-auto">
                      <h2><%= user_skill.skill.name %></h2>
                      <!-- <p><%#= user_skill.level.capitalize %></p> -->
                      <div class="d-flex"><%= "<div class='level'></div>".html_safe * (UsersSkill.levels[user_skill.level]+1) %></div>
                    </div>
                    <span class="btn btn-outline-primary rounded-pill mr-4" data-toggle="modal" data-target="#modal-recommandation-<%= user_skill.id %>">Recommend</span>
                  </div>

                  <div id="modal-recommandation-<%= user_skill.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title">Recommend this user</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <% @recommandation.users_skill = user_skill %>
                          <%= simple_form_for([@user, @recommandation], remote: true) do |f| %>
                            <%= f.input :users_skill_id, as: :hidden, value: @recommandation.users_skill.id %>
                            <%= f.input :content %>
                            <%= f.button :submit, class: 'btn btn-outline-primary' %>
                          <% end -%>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                        </div>
                      </div>
                    </div>
                  </div>
                  <% unless user_skill.recommandations.blank? %>
                    <div class="recommandations">
                      <h5>Recommendations</h5>
                      <div class="recommendations-list">
                        <div>
                          <% user_skill.recommandations.each do |recommandation| %>
                            <p><%= recommandation.user.username %>: <%= recommandation.content %></p>
                          <% end -%>

                        </div>
                      </div>

                    </div>
                  <% end -%>
                <% end -%>
              <% else %>
                <p>No current skills.</p>
              <% end -%>
            </div>
          </div>
            <div class="card rounded-lg">
              <div class="card-header text-center">
                <h2>Experiences</h2>

              </div>
              <div class="card-body">
                <% unless @experiences.blank? %>
                  <div class="experiences">
                    <ul>
                      <% @experiences.each do |experience| %>
                        <li class="mr-auto">
                          <strong>From:</strong> <%= experience.start_date %> <strong>To:</strong> <%= experience.end_date.nil? ? "Currently work here" : experience.end_date %><br>
                          <em><%= experience.content %></em>
                        </li>
                      <% end -%>

                    </ul>
                  </div>
                <% else %>
                  <p>No experiences.</p>
                <% end %>

              </div>
            </div>
        </div>

      </div>
    <% elsif @user.role == "recruiter" %>
      <div class="card rounded-lg mb-3">
        <div class="card-header text-center">
          <h2>Jobs available</h2>
        </div>
        <div class="card-body">
          <% unless @jobs.blank? %>
            <%== pagy_bootstrap_nav(@pagy) %>
            <div class="cards">
              <% @jobs.where(visible: true).each do |job| %>
                <div class="card-job rounded-pill">
                  <div class="card-job-infos">
                    <h2><%= link_to job.title, job_path(job) %></h2>
                    <p><%= job.description.gsub(/(<[^>]+>)/, '').truncate(150, separator: ' ') %></p>
                  </div>
                </div>
              <% end -%>
            </div>
          <% else %>
            <p>No jobs available.</p>
          <% end -%>
        </div>
      </div>
    <% end -%>
    <div class="row">
      <div class="col-12 col-lg-6">
        <div class="card mb-3 rounded-lg">
          <div class="card-header text-center">
            <h2>Followers</h2>
          </div>
          <div class="card-body">

            <% unless @user.followees.blank? %>
              <% @user.followees.each do |follower| %>
                <%= link_to follower.follower.username, user_path(follower.follower), class: 'btn btn-outline-secondary rounded-pill mb-1' %>
              <% end -%>
            <% else %>
              <p>No followers.</p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="card rounded-lg">
          <div class="card-header text-center">
            <h2>Followees</h2>
          </div>
          <div class="card-body">
            <% unless @user.followers.blank? %>
              <% @user.followers.each do |followee| %>
                <%= link_to followee.followee.username, user_path(followee.followee), class: 'btn btn-outline-secondary rounded-pill mb-1' %>
              <% end -%>
            <% else %>
              <p>No followees.</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

</div>