config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :articles
  resources :jobs do
    resources :jobs_applications, only: :create
  end
  resources :skills, only: [] do
    get "search", on: :collection
  end
  resources :activities, only: [:index]
  resources :followings_jobs, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :followings_users, only: [:create, :destroy]
    resources :messages do
      get "messages-unread", on: :collection
    end
    resources :chatrooms, only: :show do
      post "mark-as-read", on: :member
    end
    resources :recommandations, only: :create
  end
  namespace :my do
    resources :users, only: [:show] do
      resources :users_skills
      resources :experiences
      resources :jobs
      resources :jobs_applications, only: [] do
        get 'my-jobs-applications', on: :collection
        get 'my-jobs-applicants', on: :collection
      end
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
     © <%= mail_to "renewme.fr@gmail.com", "ReNewMe" %> 2021
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo3-renewme.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= active_link_to "Home", root_path, class: "nav-link", active: :exclusive %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Users", users_path, class: "nav-link", active: :exclusive %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Jobs", jobs_path, class: "nav-link", active: :exclusive %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Articles", articles_path, class: "nav-link", active: :exclusive %>
        </li>
        <li class="nav-item dropdown">
          <div id="messages-unread" data-user-id="<%= current_user.id %>"></div>
          <% if current_user.profile_picture.attached? %>
            <%= cl_image_tag current_user.profile_picture.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
           <%= image_tag "no-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end -%>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <span class="username">Welcome <%= current_user.username %></span>
            <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Profile", my_user_path(current_user), class: "dropdown-item" %>

            <% if current_user.role == "candidate" %>
              <%= link_to "My Jobs", my_jobs_applications_my_user_jobs_applications_path(current_user), class: "dropdown-item" %>
            <% end -%>
            <% if current_user.role == "recruiter" %>
              <%#= link_to "My Jobs", my_user_jobs_path(current_user), class: "dropdown-item" %>
              <%= link_to "My Jobs", my_jobs_applicants_my_user_jobs_applications_path(current_user), class: "dropdown-item" %>
            <% end -%>
            <div style="position:relative;"><%= link_to "Messages", user_messages_path(current_user), class: "dropdown-item" %><div id="messages-unread-menu"></div></div>
            <%= link_to "Activity", activities_path, class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn-outline-white mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn-outline-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>