config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :articles
  resources :jobs do
    resources :jobs_applications, only: :create
  end
  resources :skills, only: [] do
    get "search", on: :collection
  end
  resources :activities, only: [:index]
  resources :followings_jobs, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :followings_users, only: [:create, :destroy]
    resources :messages do
      get "messages-unread", on: :collection
    end
    resources :chatrooms, only: :show do
      post "mark-as-read", on: :member
    end
    resources :recommandations, only: :create
  end
  namespace :my do
    resources :users, only: [:show] do
      resources :users_skills
      resources :experiences
      resources :jobs
      resources :jobs_applications, only: [] do
        get 'my-jobs-applications', on: :collection
        get 'my-jobs-applicants', on: :collection
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include PgSearch::Model

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  enum role: [:candidate, :recruiter]

  attr_writer :login

  # see if can remove user_
  has_many :followees, class_name: 'FollowingsUser', foreign_key: :followee_id
  has_many :followers, class_name: 'FollowingsUser', foreign_key: :follower_id
  has_many :messages, dependent: :destroy
  has_many :chatrooms, -> { distinct }, through: :messages
  has_many :users_skills, dependent: :destroy
  has_many :skills, through: :users_skills
  has_many :experiences, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :jobs_applications, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :followings_jobs, dependent: :destroy
  has_one_attached :profile_picture

  validates :first_name, :last_name, :username, :job_position, :about_me, presence: true
  validates :username, uniqueness: { case_sensitive: false }, length: { minimum: 3 }
  validates :about_me, length: { minimum: 20 }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  validates :password, format: { with: /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/,
                                 message: "Complexity requirement not met. Please use: 1 uppercase,
                                  1 lowercase, 1 digit and 1 special character" }

  pg_search_scope :global_search,
    against: [:username, :job_position, :role],
    associated_against: {
      skills: [:name],
      experiences: [:content]
    },
    using: {
      tsearch: { prefix: true }
    }

  def role=(value)
    value = value.to_i if value.is_a? String
    super(value)
  end

  def find_or_create_chatroom_with(other_user)
    # chatroom = Chatroom.eager_load(:messages).where(
    #   messages: { user_id: self.id },
    #   messages: { user_id: other_user.id }
    # ).first
    chatroom = Chatroom.where("name = ? or name = ?", "#{self.username} - #{other_user.username}", "#{other_user.username} - #{self.username}").first

    if chatroom.nil?
      chatroom = Chatroom.create(name: "#{self.username} - #{other_user.username}")
      Message.create(user: self, chatroom: chatroom, content: "subscription", read: true)
      Message.create(user: other_user, chatroom: chatroom, content: "subscription", read: true)
    end
    return chatroom
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/my/experiences_controller.rb
class My::ExperiencesController < ApplicationController
  before_action :set_experience, only: [:edit, :update, :destroy]
  def new
    @experience = Experience.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} added a new experience.",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Experience added."
      redirect_to my_user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @experience.update(experience_params)
    if @experience.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} updated an experience.",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Experience updated."
      redirect_to my_user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @experience.destroy
    redirect_to my_user_path(current_user)
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:start_date, :end_date, :content)
  end
end

app/controllers/my/jobs_applications_controller.rb
class My::JobsApplicationsController < ApplicationController
  def my_jobs_applications
    @pagy, @jobs_applications = pagy(current_user.jobs_applications, items: 5)
    @pagy_follow, @followings_jobs = pagy(@current_user.followings_jobs, page_param: :page_follow, items: 5)
  end

  def my_jobs_applicants
    @pagy_jobs, @jobs = pagy(current_user.jobs, page_param: :page_jobs, items: 8)
    @pagy, @jobs = pagy(current_user.jobs.order(created_at: :desc).joins(:jobs_applications).distinct, items: 5)
  end
end

app/controllers/my/jobs_controller.rb
class My::JobsController < ApplicationController
  def index
    @pagy, @jobs = pagy(current_user.jobs, items: 8)
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} posted a new job: #{view_context.link_to @job.title, job_path(@job)}",
        user: current_user
      ) if @job.visible
      redirect_to my_user_job_path(current_user,@job)
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    if @job.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} updated the job: #{view_context.link_to @job.title, job_path(@job)}",
        user: current_user
      ) if @job.visible
      redirect_to my_user_job_path(@job)
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "You have successfully deleted this job."
    redirect_to my_user_jobs_path(current_user)
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :visible)
  end
end

app/controllers/my/users_controller.rb
class My::UsersController < ApplicationController
  def show
    @current_users_skills = UsersSkill.where(user: current_user, previous_skills: false)
    @previous_users_skills = UsersSkill.where(user: current_user, previous_skills: true)
    @experiences = Experience.where(user: current_user).order(start_date: :desc)
    @pagy, @jobs = pagy(current_user.jobs, items: 8)
  end
end

app/controllers/my/users_skills_controller.rb
class My::UsersSkillsController < ApplicationController
  before_action :set_users_skill, only: [:edit, :update, :destroy]
  def new
    @users_skill = UsersSkill.new
    @skills = Skill.all.limit(100)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    params[:users_skill][:level] = params[:users_skill][:level].to_i unless params[:users_skill][:level] == ""
    @users_skill = UsersSkill.new(users_skill_params)
    @users_skill.user = current_user
    if @users_skill.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} added a new skill: #{@users_skill.skill.name}",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Skill added."
      redirect_to my_user_path(current_user)
    else
      @skills = Skill.all
      render 'new'
    end
  end

  def edit
  end

  def update
    params[:users_skill][:level] = params[:users_skill][:level].to_i unless params[:users_skill][:level] == ""
    @users_skill.update(users_skill_params)
    if @users_skill.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} updated the skill: #{@users_skill.skill.name}",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Skill updated."
      redirect_to my_user_path(current_user)
    end
  end

  def destroy
    @users_skill.destroy
    redirect_to my_user_path(current_user)
  end

  private

  def set_users_skill
    @users_skill = UsersSkill.find(params[:id])
  end

  def users_skill_params
    params.require(:users_skill).permit(:skill_id, :level, :previous_skills)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    if params[:query] && !params[:query].empty?
      # if params[:query] =~ /(r|R){1}(e|E){1}(c|C){1}(r|R)?(u|U)?(i|I)?(t|T)?(e|E)?(r|R)?/
      #   @query = 1
      # elsif params[:query] =~ /(c|C){1}(a|A){1}(n|N){1}(d|D)?(i|I)?(d|D)?(a|A)?(t|T)?(e|E)?/
      #   @query = 0
      # end
      @role = SearchRole.new(params[:query])
      @search_roles = User.where(role: @role.get_role).where.not(visible: false, confirmed_at: nil, id: current_user)
      @full_search_array = @search_roles + User.global_search(params[:query]).where.not(visible: false, confirmed_at: nil, id: current_user)
      @full_search = User.where(id: @full_search_array.map(&:id))
      @pagy, @users = pagy(@full_search, items: 12)
    else
      @pagy, @users = pagy(User.where.not(visible: false, confirmed_at: nil, id: current_user), items: 12)
    end
  end

  def show
    @current_users_skills = UsersSkill.where(user: @user, previous_skills: false)
    @previous_users_skills = UsersSkill.where(user: @user, previous_skills: true)
    @experiences = Experience.where(user: @user).order(start_date: :desc)
    @pagy, @jobs = pagy(@user.jobs, items: 8)
    @message = Message.new
    @chatroom = current_user.find_or_create_chatroom_with(@user)
    @message.chatroom = @chatroom
    @recommandation = Recommandation.new
    @followings_user = FollowingsUser.where(followee: params[:id], follower: current_user).first
    @followings_user = FollowingsUser.new unless @followings_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/my/users/show.html.erb
<div class="container mt-3">
  <h1>My profile</h1>
  <hr>
  <div class="row mb-3">
    <div class="col-12">
      <div class="card rounded-lg">
        <div class="card-header">
          <h2>About me</h2>

        </div>
        <div class="card-body">
          <p><%= current_user.about_me %></p>

        </div>
      </div>
    </div>
  </div>
  <% if current_user.role == "candidate" %>
    <div class="row mb-3">
      <div class="col-12">
        <%= link_to 'Add a skill', new_my_user_users_skill_path(current_user),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-outline-primary rounded-pill'}  %>
        <%= link_to 'Add an experience', new_my_user_experience_path(current_user),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-experience', class: 'btn btn-outline-primary rounded-pill'}  %>

      </div>
    </div>
    <div class="row mb-3">
      <div class="col-12 col-lg-6">
        <div class="card rounded-lg mb-3">
          <div class="card-header">
            <h2>Current skills</h2>

          </div>
          <div class="card-body">

            <% unless @current_users_skills.blank? %>
              <% @current_users_skills.each do |user_skill| %>
                <div class="card-skill">
                  <div class="card-skill-infos mr-auto">
                    <h2><%= user_skill.skill.name %></h2>
                    <p><%#= user_skill.level.capitalize %></p>
                    <div class="d-flex"><%= "<div class='level'></div>".html_safe * (UsersSkill.levels[user_skill.level]+1) %></div>
                  </div>
                  <%= link_to 'Edit', edit_my_user_users_skill_path(current_user,user_skill), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-skill", class: 'btn btn-outline-primary rounded-pill mr-1'}  %>
                  <div id="modal-skill" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content"></div>
                    </div>
                  </div>
                  <%= link_to 'Delete', my_user_users_skill_path(current_user,user_skill), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger rounded-pill mr-3' %>
                </div>
                <% unless user_skill.recommandations.blank? %>
                  <div class="recommandations">
                    <h5>Recommendations</h5>
                    <div class="recommendations-list">
                      <div>
                        <% user_skill.recommandations.each do |recommandation| %>
                          <p><%= recommandation.user.username %>: <%= recommandation.content %></p>
                        <% end -%>

                      </div>
                    </div>

                  </div>
                <% end -%>
              <% end -%>
            <% else %>
              <p>No current skills.</p>
            <% end %>
            <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="card rounded-lg mb-3">
          <div class="card-header">
            <h2>Previous skills</h2>

          </div>
          <div class="card-body">
            <% unless @previous_users_skills.blank? %>
              <% @previous_users_skills.each do |user_skill| %>
                <div class="card-skill previous-skills">
                  <div class="card-skill-infos mr-auto">
                    <h2><%= user_skill.skill.name %></h2>
                    <p><%#= user_skill.level.capitalize %></p>
                    <div class="d-flex"><%= "<div class='level'></div>".html_safe * (UsersSkill.levels[user_skill.level]+1) %></div>
                  </div>
                  <%= link_to 'Edit', edit_my_user_users_skill_path(current_user,user_skill), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-skill", class: 'btn btn-outline-primary rounded-pill mr-1'}  %>
                  <%= link_to 'Delete', my_user_users_skill_path(current_user,user_skill), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger rounded-pill mr-3' %>
                </div>
                <% unless user_skill.recommandations.blank? %>
                  <div class="recommandations">
                    <h5>Recommendations</h5>
                    <div class="recommendations-list">
                      <div>
                        <% user_skill.recommandations.each do |recommandation| %>
                          <p><%= recommandation.user.username %>: <%= recommandation.content %></p>
                        <% end -%>

                      </div>
                    </div>

                  </div>
                <% end -%>
              <% end -%>
            <% else %>
              <p>No current skills.</p>
            <% end -%>
          </div>
        </div>
        <div class="card rounded-lg">
          <div class="card-header">
            <h2>Experiences</h2>

          </div>

          <div class="card-body">
              <% unless @experiences.blank? %>
              <div class="experiences">
                <ul>
                <% @experiences.each do |experience| %>

                  <div class="d-flex">


                    <li class="mr-auto">
                      <strong>From:</strong> <%= experience.start_date %> <strong>To:</strong> <%= experience.end_date.nil? ? "Currently work here" : experience.end_date %><br>
                      <em><%= experience.content %></em>
                    </li>
                    <div>
                      <table>
                        <tr>
                          <td>
                      <%= link_to 'Edit', edit_my_user_experience_path(current_user,experience), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-experience", class: 'btn btn-outline-primary rounded-pill mr-1'} %>

                          </td>
                          <td>
                      <%= link_to 'Delete', my_user_experience_path(current_user,experience), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger rounded-pill' %>

                          </td>
                        </tr>
                      </table>
                    </div>

                  </div>

                <% end -%>
              </div>

                </ul>
              <% else %>
                <p>No experiences.</p>
              <% end %>

            <div id="modal-experience" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% elsif current_user.role == "recruiter" %>
      <div class="card rounded-lg mb-3">
        <div class="card-header">
          <h2>My Jobs</h2>
        </div>
        <div class="card-body">
          <%== pagy_bootstrap_nav(@pagy) %>
          <% unless @jobs.blank? %>
            <div class="cards">
              <% @jobs.each do |job| %>
                <div class="card-job rounded-pill">
                  <div class="card-job-infos">
                    <h2><%= link_to job.title, job_path(job) %></h2>
                    <div class="card-job-description mb-1"><%= job.description.gsub(/(<[^>]+>)/, '').truncate(150, separator: ' ') %></div>
                    <p>Published: <%= job.visible ? "Yes" : "No" %></p>
                  </div>
                </div>
              <% end -%>
            </div>
          <% else %>
            <p>You didn't post any jobs yet.</p>
          <% end -%>
        </div>
      </div>
  <% end -%>
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="card rounded-lg mb-3">
        <div class="card-header">
          <h2>Followers</h2>

        </div>
        <div class="card-body">

          <% unless current_user.followees.blank? %>
            <% @current_user.followees.each do |follower| %>
              <%= link_to follower.follower.username, user_path(follower.follower), class: 'btn btn-outline-secondary rounded-pill mb-1' %>
            <% end -%>
          <% else %>
            <p>No followers.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="card rounded-lg">
        <div class="card-header">
          <h2>Followees</h2>

        </div>
        <div class="card-body">
          <% unless @current_user.followers.blank? %>
            <% @current_user.followers.each do |followee| %>
              <%= link_to followee.followee.username, user_path(followee.followee), class: 'btn btn-outline-secondary rounded-pill mb-1' %>
            <% end -%>
          <% else %>
            <p>No followees.</p>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>