config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :articles
  resources :jobs do
    resources :jobs_applications, only: :create
  end
  resources :skills, only: [] do
    get "search", on: :collection
  end
  resources :activities, only: [:index]
  resources :followings_jobs, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :followings_users, only: [:create, :destroy]
    resources :messages do
      get "messages-unread", on: :collection
    end
    resources :chatrooms, only: :show do
      post "mark-as-read", on: :member
    end
    resources :recommandations, only: :create
  end
  namespace :my do
    resources :users, only: [:show] do
      resources :users_skills
      resources :experiences
      resources :jobs
      resources :jobs_applications, only: [] do
        get 'my-jobs-applications', on: :collection
        get 'my-jobs-applicants', on: :collection
      end
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :jobs_applications, dependent: :destroy
  validates :title, :description, presence: true
  include PgSearch::Model

  pg_search_scope :job_search,
    against: [:title, :description],
    associated_against: {
      user: [:username]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: :show
  def index
    if params[:query] && !params[:query].empty?
      @pagy, @jobs = pagy(Job.job_search(params[:query]).where.not(visible: false, user_id: current_user), items: 12)
    else
      @pagy, @jobs = pagy(Job.where.not(visible: false, user_id: current_user), items: 12)
    end
  end

  def show
    @jobs_application = JobsApplication.where(user: current_user, job: @job).first
    @jobs_application = JobsApplication.new if @jobs_application.nil?
    @followings_job = FollowingsJob.where(job: params[:id], user: current_user).first
    unless @followings_job
      @followings_job = FollowingsJob.new
      @followings_job.job = @job
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end
end

app/controllers/my/experiences_controller.rb
class My::ExperiencesController < ApplicationController
  before_action :set_experience, only: [:edit, :update, :destroy]
  def new
    @experience = Experience.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} added a new experience.",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Experience added."
      redirect_to my_user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @experience.update(experience_params)
    if @experience.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} updated an experience.",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Experience updated."
      redirect_to my_user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @experience.destroy
    redirect_to my_user_path(current_user)
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:start_date, :end_date, :content)
  end
end

app/controllers/my/jobs_applications_controller.rb
class My::JobsApplicationsController < ApplicationController
  def my_jobs_applications
    @pagy, @jobs_applications = pagy(current_user.jobs_applications, items: 5)
    @pagy_follow, @followings_jobs = pagy(@current_user.followings_jobs, page_param: :page_follow, items: 5)
  end

  def my_jobs_applicants
    @pagy_jobs, @jobs = pagy(current_user.jobs, page_param: :page_jobs, items: 8)
    @pagy, @jobs = pagy(current_user.jobs.order(created_at: :desc).joins(:jobs_applications).distinct, items: 5)
  end
end

app/controllers/my/jobs_controller.rb
class My::JobsController < ApplicationController
  def index
    @pagy, @jobs = pagy(current_user.jobs, items: 8)
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} posted a new job: #{view_context.link_to @job.title, job_path(@job)}",
        user: current_user
      ) if @job.visible
      redirect_to my_user_job_path(current_user,@job)
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    if @job.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} updated the job: #{view_context.link_to @job.title, job_path(@job)}",
        user: current_user
      ) if @job.visible
      redirect_to my_user_job_path(@job)
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "You have successfully deleted this job."
    redirect_to my_user_jobs_path(current_user)
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :visible)
  end
end

app/controllers/my/users_controller.rb
class My::UsersController < ApplicationController
  def show
    @current_users_skills = UsersSkill.where(user: current_user, previous_skills: false)
    @previous_users_skills = UsersSkill.where(user: current_user, previous_skills: true)
    @experiences = Experience.where(user: current_user).order(start_date: :desc)
    @pagy, @jobs = pagy(current_user.jobs, items: 8)
  end
end

app/controllers/my/users_skills_controller.rb
class My::UsersSkillsController < ApplicationController
  before_action :set_users_skill, only: [:edit, :update, :destroy]
  def new
    @users_skill = UsersSkill.new
    @skills = Skill.all.limit(100)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    params[:users_skill][:level] = params[:users_skill][:level].to_i unless params[:users_skill][:level] == ""
    @users_skill = UsersSkill.new(users_skill_params)
    @users_skill.user = current_user
    if @users_skill.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} added a new skill: #{@users_skill.skill.name}",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Skill added."
      redirect_to my_user_path(current_user)
    else
      @skills = Skill.all
      render 'new'
    end
  end

  def edit
  end

  def update
    params[:users_skill][:level] = params[:users_skill][:level].to_i unless params[:users_skill][:level] == ""
    @users_skill.update(users_skill_params)
    if @users_skill.save
      Activity.create!(
        description: "#{view_context.link_to current_user.username, user_path(current_user)} updated the skill: #{@users_skill.skill.name}",
        user: current_user
      ) if current_user.visible
      flash[:notice] = "Skill updated."
      redirect_to my_user_path(current_user)
    end
  end

  def destroy
    @users_skill.destroy
    redirect_to my_user_path(current_user)
  end

  private

  def set_users_skill
    @users_skill = UsersSkill.find(params[:id])
  end

  def users_skill_params
    params.require(:users_skill).permit(:skill_id, :level, :previous_skills)
  end
end

app/views/my/jobs/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Add a new job</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= simple_form_for([current_user, @job], url: my_user_jobs_path, remote: true) do |f| %>

    <%= f.input :title, label: "Enter the title of the job" %>

    <%= f.input :description, as: :hidden %>
    <trix-editor input="job_description" style="height: 400px;overflow-y:auto"></trix-editor>
    <%#= f.input :visible %>
    <div class="custom-control custom-switch mt-3 mb-3">
      <%= f.check_box :visible, class: "custom-control-input", id: "customSwitch1" %>
      <label class="custom-control-label" for="customSwitch1">Make your job visible and searchable</label>
    </div>
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
    <button type="button" class="btn btn-outline-secondary ml-3" data-dismiss="modal">Close</button>
  <% end -%>
</div>

app/views/my/jobs/edit.html.erb
<div class="container mt-3">
  <div class="card rounded-lg">
    <div class="card-header">
      <h1>Edit Job</h1>
    </div>
    <div class="card-body">
      <%= simple_form_for([current_user, @job], url: my_user_job_path, remote: true) do |f| %>

        <%= f.input :title, label: "Enter the title of the job" %>

        <%= f.input :description, as: :hidden %>
        <trix-editor input="job_description"></trix-editor>
        <%#= f.input :visible %>
        <div class="custom-control custom-switch mt-3 mb-3">
          <%= f.check_box :visible, class: "custom-control-input", id: "customSwitch1" %>
          <label class="custom-control-label" for="customSwitch1">Make your job visible and searchable</label>
        </div>
        <%= f.button :submit, class: 'btn btn-outline-primary rounded-pill' %>
        <%= link_to 'Back', my_user_jobs_path, class: 'btn btn-outline-primary rounded-pill' %>
      <% end -%>

    </div>
</div>

app/views/my/jobs/index.html.erb
<div class="container mt-3">
  <div class="card rounded-lg">
    <div class="card-header">
      <h1>My Jobs</h1>
    </div>
    <div class="card-body">
      <!-- <div class="row">
        <div class="col-12 col-md-9">
          <%#= form_tag users_path, method: :get, class: "form-inline mb-3" do %>
            <table>
            </table>
          <%# end %>
        </div>
      </div> -->
      <div class="row">
        <div class="col-12 col-lg-9">
          <%= link_to "Post a new job", new_my_user_job_path, class: 'btn btn-outline-primary rounded-pill mb-3', remote: true, "data-toggle": "modal", "data-target": "#modal-job"  %>
        </div>
        <div class="col-12 col-lg-2">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      </div>
      <div id="modal-job" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content"></div>
        </div>
      </div>
      <% unless @jobs.blank? %>
        <div class="cards mt-3">
            <% @jobs.each do |job| %>
              <div class="card-job">
                <div class="card-job-infos">
                  <h2><%= link_to job.title, my_user_job_path(current_user, job) %></h2>
                  <div class="card-job-description mb-1"><%= job.description.gsub(/(<[^>]+>)/, '').truncate(150, separator: ' ') %></div>
                  Published: <%= job.visible ? "Yes" : "No" %><br>
                  <%= link_to "Edit", edit_my_user_job_path(current_user,job) %>
                  <%= link_to "Delete", my_user_job_path(current_user,job), method: :delete %>

                </div>

              </div>
            <% end %>
        </div>
      <% else %>
        <p>You didn't post any jobs yet.</p>
      <% end -%>
    </div>
  </div>
</div>

app/views/my/jobs/new.html.erb
<%= form_for @job do |format| %>

  <%= f.label :name, "Enter the name of the job" %>
  <%= f.text_field :name %>

  <%= f.label :title, "Enter the title of the job" %>
  <%= f.text_field :title %>

  <%= f.label :content, "Enter the content of the job" %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/my/jobs/new.js.erb
$("#modal-job").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-job").modal();
// var cloudName = "df9n6rd5h";
// var unsignedUploadPreset = 'y7vthcmn';

// var HOST = `https://api.cloudinary.com/v1_1/${cloudName}/upload`;

// addEventListener("trix-attachment-add", function(event) {
//   if (event.attachment.file) {
//     uploadFileAttachment(event.attachment)
//   }
// })

// function uploadFileAttachment(attachment) {
//   uploadFile(attachment.file, setProgress, setAttributes)

//   function setProgress(progress) {
//     attachment.setUploadProgress(progress)
//   }

//   function setAttributes(attributes) {
//     attachment.setAttributes(attributes)
//   }
// }

// function uploadFile(file, progressCallback, successCallback) {
//   var formData = createFormData(file)
//   var xhr = new XMLHttpRequest()

//   xhr.open("POST", HOST, true)

//   xhr.upload.addEventListener("progress", function(event) {
//     var progress = event.loaded / event.total * 100
//     progressCallback(progress)
//   })

//   xhr.onreadystatechange = function(e) {
//     if (xhr.readyState == 4 && xhr.status == 200) {
//       var response = JSON.parse(xhr.responseText);
//       var url = response.secure_url;
//       //document.querySelector('figure').appendChild(img)
//       var attributes = {
//           url: url ,
//           href: url
//       }
//       successCallback(attributes)
//       //document.getElementById('job_description').value = document.getElementById('job_description').value + `<img src="${url}" width="50%" height="auto" margin="0 auto">`;
//     }
//   };
//   xhr.send(formData)

// }

// function createFormData(file) {
//   var data = new FormData()
//   data.append('upload_preset', unsignedUploadPreset);
//   data.append("Content-Type", file.type)
//   data.append("file", file)
//   return data
// }

app/views/my/jobs/show.html.erb
<div class="container mt-3">
  <div class="card rounded-lg">
    <div class="card-header">
      <h1><%= @job.title %></h1>

    </div>
    <div class="card-body">
      <%= link_to "Edit", edit_my_user_job_path(current_user,@job), class: 'btn btn-outline-primary rounded-pill' %>
      <%= link_to "Delete", my_user_job_path(current_user,@job), method: :delete, class: 'btn btn-outline-danger rounded-pill' %>
      <%#= link_to "Back to List", my_user_jobs_path , class: 'btn btn-outline-secondary rounded-pill'%>
      <%= link_to "Back to List", my_jobs_applicants_my_user_jobs_applications_path(current_user) , class: 'btn btn-outline-secondary rounded-pill'%>
      <hr>
      <%= @job.description.html_safe %>


    </div>
  </div>

</div>